"""Added weather_record table

Revision ID: c9c5a4d5a64a
Revises: 
Create Date: 2025-04-16 11:32:43.321829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa 


# revision identifiers, used by Alembic.
revision: str = 'c9c5a4d5a64a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(50), nullable=False),
    sa.Column('wind_degree', sa.Integer(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Enum('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', name='winddirectionenum'), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.Column('air_quality_carbon_monoxide', sa.Float(), nullable=False),
    sa.Column('air_quality_ozone', sa.Float(), nullable=False),
    sa.Column('air_quality_nitrogen_dioxide', sa.Float(), nullable=False),
    sa.Column('air_quality_sulphur_dioxide', sa.Float(), nullable=False),
    sa.Column('air_quality_pm2', sa.Float(), nullable=False),
    sa.Column('air_quality_pm10', sa.Float(), nullable=False),
    sa.Column('air_quality_us_epa_index', sa.Integer(), nullable=False),
    sa.Column('air_quality_gb_defra_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'weather_record' in inspector.get_table_names():
        op.drop_table('weather_record')

    # Додатково — перевірка для PostgreSQL enum
    if bind.dialect.name == 'postgresql':
        op.execute("DROP TYPE IF EXISTS winddirectionenum;")